version: 0.2

phases:
  install:
    commands:
      - pip install -r requirements.txt -t ./

  build:
    commands:
      - PR=`echo $CODEBUILD_WEBHOOK_TRIGGER | sed -e 's/\///'`
      - APP_NAME=my-review-apps-$PR
      - aws s3 mb s3://$APP_NAME
      - sam package --template-file template.yaml |
        --output-template-file serverless-output.yaml |
        --s3-bucket $APP_NAME
      - sam deploy |
        --template-file ./serverless-output.yaml |
        --stack-name $APP_NAME |
        --capabilities CAPABILITY_IAM