version: 0.2

phases:
  install:
    commands:
      - pip install -r requirements.txt -t ./

  build:
    commands:
      - PR=`echo $CODEBUILD_WEBHOOK_TRIGGER | sed -e 's/\///'`
      - echo $PR
      - APP_NAME=my-review-apps-$PR
      - echo $APP_NAME
      - aws s3 mb s3://$APP_NAME