version: 0.2

phases:
  install:
    commands:
      - pip install -r requirements.txt -t ./

  build:
    commands:
      - PR=`echo $CODEBUILD_WEBHOOK_TRIGGER | sed -e 's/\///'
      - APP_NAME=my-review-apps-$PR
      - aws s3 mb $APP_NAME