version: 0.2

phases:
  install:
    commands:
      - pip install aws-sam-cli==0.6.1

  pre_build:
    commands: 
      - PR=`echo $CODEBUILD_WEBHOOK_TRIGGER | sed -e 's/\///'`
      - APP_NAME=my-review-apps-$PR
      - aws s3 ls s3://$APP_NAME 2> /dev/null
      - if [ $? != 0 ]; then aws s3 mb s3://$APP_NAME; fi

  build:
    commands:
      - pip install -r requirements.txt -t hello_world/build
      - cp hello_world/*.py hello_world/build/

      - sam package --template-file template.yaml --output-template-file serverless-output.yaml --s3-bucket $APP_NAME
      - sam deploy --template-file ./serverless-output.yaml --stack-name $APP_NAME --capabilities CAPABILITY_IAM